### ISSUE TITLE
getting We can't connect to the service you need right now

### ISSUE THREAD

**Issue by atulgit** [auth0/Auth0.Windows.UWP#14]
I am getting following error and not able to proceed with signin. 

![image](https://cloud.githubusercontent.com/assets/3737792/26340994/10133930-3faf-11e7-90e0-84ad77bfd63b.png)

Please Help!

**Comment by jerriep** [comment]
Hi, 

Are you using a proxy server or Fiddler while testing by any chance?

Also, I cannot really assist based just on the error message you gave me above. Please send me a reproducible sample application

Thank you

**Comment by atulgit** [comment]
This is the only sample application (downloaded from github) I am using. I just replaced domain name and client Id in sample code.

I have not changed anything else and I am not using any proxy server.
Is this sample working at your end?

**Comment by jerriep** [comment]
I have tested it and it works fine.

However, this is also not the correct library to use anymore. Please follow our UWP quickstart over here:
https://auth0.com/docs/quickstart/native/windows-uwp-csharp

This uses our new [Auth0 OIDC Client](https://auth0.github.io/auth0-oidc-client-net/) .

If you have issues with that, please create a ticket on the Auth0 Support centre (https://support.auth0.com/) if you're a paid/trial customer, or alternatively post on the Auth0 Community Forums (https://community.auth0.com/) if you are a free customer

**Comment by RikardoPons** [comment]
I have the same problem I am using   Auth0 OIDC Client . for UWP Someone knows how to solve this issue?
Thank you!

**Comment by jerriep** [comment]
@RikardoPons The only situation where I have seen this happen was when something like Fiddler. 

* Are you perhaps using Fiddler (or another type of proxy)?

* Is there anything else "unusual" about your environment?

* Any chance of posting sample of your source code here?

**Comment by DeltaRanger509** [comment]
@jerriep I'm having this same issue.  I'm using the demo downloadabled from here: https://auth0.com/docs/quickstart/native/windows-uwp-csharp

After turning on WebAuthenticationBroker operational logging using the instructions here: https://msdn.microsoft.com/en-us/library/windows/apps/xaml/Hh750287.aspx  I discovered that the Auth0 library was attempting to redirect to https://myAccountName.auth0.com/mobile and failing with a 403 because that wasn't a configured callback on my Auth0 settings.

After adding this URL to my list of callbacks, the LoginAsync method is still failing.  The error message is: "Error validating token response: Access token is missing on token response.".  Looking back at the WebAuthenticationBroker operational log, I'm seeing this message as the last in the message chain: "AuthHost disallowed UrlAction: 0x2200 for URL: <https://login.live.com/ppsecure/post.srf?response_type=code&redirect_uri=https%3A%2F%2Flogin.auth0.com%2Flogin%2Fcallback&scope=wl.signin&state=REDACTED&client_id=REDACTED&contextid=REDACTED&bk=REDACTED&uaid=REDACTED&pid=REDACTED>.".

Any idea why it would be redirecting through that URL or why it was redirecting to https://myAccountName.auth0.com/mobile in the first place?  How should I proceed from here?

**Comment by jerriep** [comment]
@DeltaRanger509 Can you please tell me a few things:

1. First of all, I am not sure whether you are using the `Auth0.Windows.UWP` NuGet package, or the `Auth0.OidcClient.UWP` NuGet package. Can you please clarify that for me?

2. When the Auth0 Lock opens, are you signing in with your Microsoft account? 

> Any idea why it would be redirecting through that URL or why it was redirecting to https://myAccountName.auth0.com/mobile in the first place? How should I proceed from here?

Yeah, this does not make sense. The new `Auth0.OidcClient.UWP` NuGet package should not try and redirect there, which is why I asked question (1)

**Comment by jerriep** [comment]
BTW, thanks for that link to the operational logging instructions. I did not know about that. It will be very helpful in trying to track down issues

**Comment by jerriep** [comment]
OK, there does indeed seem to be an issue with the version of `Auth0.OidcClient.UWP` on NuGet where the callback URL is wrong. It should not be he `.../mobile` endpoint. 

I will release an update later to correct this.

**Comment by jerriep** [comment]
@deltaranger509 I release version 1.1.0 of the OIDC Client for UWP. The Callback URL needs to be configured as per this document:
https://auth0.com/docs/quickstart/native/windows-uwp-csharp#set-up-the-auth0-callback-url

**Comment by DeltaRanger509** [comment]
@jerriep I'm using the OIDC client.  I updated to the latest package, and the operational WebAuthenticationBroker log now happily indicates that I'm making it all the way to back to the callback URL (AuthHost terminated navigation with HTTP POST data: <code=8yoiTvTdsfm81opK&state=bec18f5401df02c6a60ca4f62fd4d556> at URL: <ms-app://s-1-REDACTED/> matching termination URL: <ms-app://s-1-REDACTED/>.), however, the client library still returns the error I indicated above: "Error validating token response: Access token is missing on token response."

I'm seeing this when I sign in with both Google and Microsoft account providers.  I get a chance to enter my password information, go through 2-factor for the account provider, and then I always get an error response back.

I'll try and get a Fiddler trace later today if you're not able to repro this with the demo code to see what the response actually contains.

**Comment by jerriep** [comment]
Do you also get this when you sign in using a normal username/password - i.e. an Auth0 database user, not a social user?

I tried using Google earlier, and did not experience any errors.

It is already quite late over here. I will play again with this tomorrow to see whether I can reproduce.

**Comment by DeltaRanger509** [comment]
@jerriep Yes, I get the same error with a username/password user.

**Comment by jerriep** [comment]
Can you please turn on logging in the event viewer as per the document you posted earlier, and then attempt to do a login. Save the events from that session to a file and email it to me at jerrie [at] auth0.com

If you are hesitant to send me a file which potentially contains sensitive information about your Auth0 Client, you can just register another temporary Client in Auth0 and use that for now.

I will then look at this further tomorrow

**Comment by TastesLikeTurkey** [comment]
I'm getting the "can't connect to service" issue as well. I'm definitely using version 1.1.0 of the OIDC package, and I've followed [this tutorial](https://manage.auth0.com/#/clients/ONkJK1jxw7mDXUWDXOwtKesYRIdmmgG7/quickstart) exactly, but it still refuses to connect.

**Comment by jerriep** [comment]
@TastesLikeTurkey Have you ensured in the Auth0 Dashboard that your Client (1) is set to "Native" for the Client Type, (2) is using RS256 signed tokens and (3) that you have enabled the OIDC conformant flag?

**Comment by TastesLikeTurkey** [comment]
@jerriep  Here's my setup:
![clienttype](https://user-images.githubusercontent.com/9746255/27481547-14f221a6-57eb-11e7-8bfd-41189acfc89f.PNG)
![callback](https://user-images.githubusercontent.com/9746255/27481550-194abd8a-57eb-11e7-97de-e7b7e0d776d4.PNG)
![tokentype](https://user-images.githubusercontent.com/9746255/27481563-2273e79c-57eb-11e7-8cc0-2eb52144cf7b.PNG)
![nuget](https://user-images.githubusercontent.com/9746255/27481569-286fd5c0-57eb-11e7-8841-3c5d31f27124.PNG)
![code](https://user-images.githubusercontent.com/9746255/27481573-2baf3956-57eb-11e7-82fb-5cda61de9bd7.PNG)

**Comment by jerriep** [comment]
@TastesLikeTurkey You are not working through a proxy, or running Fiddler, right? Because that can also cause this issue.

If that is not the problem, then please enable the Operation Logs as described here:
https://msdn.microsoft.com/en-us/library/windows/apps/xaml/Hh750287.aspx

Then try and do an authentication request again, and save those logs for me to a file and send it off to jerrie [at] auth0.com so I can try and figure this one out

**Comment by TastesLikeTurkey** [comment]
@jerriep  Negative on both counts. I've sent you an email with the event logs.
