### ISSUE TITLE
Third party access_token doesn't exist

### ISSUE THREAD

**Issue by mikecousins** [auth0/Auth0.Windows.UWP#8]
https://auth0.com/docs/quickstart/native/windows-uwp-csharp

This page says that we should be able to call `var user = await auth0.LoginAsync();` and we should get an object which will have an access token for a certain identity available now:

```
/*
    Use this object to do wonderful things, e.g.:
      - get user email => user.Profile["email"].ToString()
      - get facebook/google/twitter/etc access token => user.Profile["identities"][0]["access_token"]
      - get Windows Azure AD groups => user.Profile["groups"]
      - etc.
*/
```

The access_token field does not exist when I do this. I don't know if it's related to it being Yahoo or not, but it's definitely not there.

**Comment by jerriep** [comment]
@mikecousins This library is not supported anymore, and this issue is terribly old - so not sure whether this is an issue anymore? 

Please follow our [Auth0 UWP Quickstart](https://auth0.com/docs/quickstart/native/windows-uwp-csharp) with guidance on how to use the new Auth0 OIDC Client

In order to obtain a 3rd party token, you will need to call the [User Info endpoint](https://auth0.com/docs/api/authentication#get-user-info), passing along the `access_token`.

If you have any issues with this, please open a new issue on the https://github.com/auth0-community/auth0-uwp-oidc-samples repo and ping my username directly so I can look into it.
